### PR TITLE
Update event_bus.dart

### PR DESCRIPTION
**Pull request by Vadaski**
Update EventBus constructor to allow custom  EventBus.

### CODE REVIEW

**Comment by marcojakob** [comment]
Can you provide a small example of how you would use the EventBus like this?

**Comment by Vadaski** [comment]
sure,here is the example:https://github.com/OpenFlutter/Flutter-Notebook/tree/master/mecury_project/example/event_bus_demo

**Comment by marcojakob** [comment]
Thanks for the example. It's not very minimal but I get the picture.

What's the reason you are not using the `BehaviorSubject` directly in your example?

By adding an optional `StreamController` as parameter to the `EventBus` constructor the interface becomes a bit confusing. The `sync` parameter is ignored when a `controller` is specified.

I think by using special controllers, the behavior of EventBus can become hard to understand. I think it's better to use something like `BehaviorSubject` directly so that the special behavior is expected.

**Comment by Vadaski** [comment]
Thank you to remind me! I agree with the sync parameter will ignored when a controller is specified.I overlooked it. 

This example shows two pages rely on CountEvent.They use StreamBuilder to listen for this event. If I use StreamController.broadcast I have to fire the Event after streamBuilder listen this stream.Otherwise I won't get the message.
BehaviorSubject can add last event to listener when they first listen.I don't need to care when listener listens.So I just fire the event before streamBuilder first listen.As you can see I fired the first CountEvent in the main function. EventBus become more powerful and easy to use.

 I think using another constructor might be the better solution.

```
  EventBus({bool sync = false})
      : _streamController = StreamController.broadcast(sync: sync);

  EventBus.custom(StreamController controller) : _streamController = controller;
```

**Comment by marcojakob** [comment]
Thanks @Vadaski. I've made a small change and merged it. It's now as v1.1.0 on pub.

**Comment by Vadaski** [comment]
Great! I'm happy to make eventbus better. Thank you@marcojakob！

**Pull request merged**
